language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: "xyoraclenetwork"
    token:
      ssecure: "Q2HCoSeg2zNk+hksSkFGNnDy7/IpuiGDTYUIG5RwqxSx1fMnBTO3f96/pbpQsc/BLkNRdYwRl0TgpCKApE8RBBcfReh1FygMePqyBfX6dWZfdN8xZHE5opJtFuZzjWAjucZSZT1ZC9tfNyQte0Y5p/1uybJGMsvZ3+Ocic2I84CpT5fXsJx1Gbe+gNblzzq5q+MpxedZYVfqJTflMJjzxGiN61+0ABxg5W5zJ1233oVbzqbs4COGhOk6yPOW9DZS9bL8CHAYeX74l6JfXi+d6qrEOyRzzY+T8Mz8iVv7OeHm6tOpFaquQ95el8Xxmb6WwDNQC/8PauAMvV4BMOMqvNTFqdbHTae6/A/rhI38wI6wuE7ypW1aAvT0Fub+loAfPnW8sm2dz3GH+zSdqc/PIVnFe5VZ0V1RG+eqEmPvZWol7XsWKMJZ+GjkA8+mFxS1P91hszNU3duG9Xt8wOfdsfvFiQDFYYoAQXc+uZUStVKmKN6aGDBVvDM4XCU6cEKperMswsaLb6yGSpKF0GRVUh3p2AThaa6BMnkgQPnebBYXssTC8ukwpb46CY6h9CKRteFpi/Ne3R8EmSXEzjrA1iBfcqiaUmxv4n/3bvi4ZJ/kvNE+hUkq8plneqTTK0DR0i1uy/Lvw4gkxRe+ZlbiYKUlkJHA5/MVX3cs1QqPXrc="
install:
  - yarn install
script:
  - yarn build
  - sonar-scanner